### ISSUE TITLE
d.tsファイルの自動生成

### ISSUE THREAD

**Issue by soeklgb** [Spoonail-Iroiro/maginai#15]
union.jsで定義されているクラスのd.tsファイルがあればmaginaiやModの開発が楽になるはずです。
しかしunion.jsは巨大なので手動でd.tsファイルを作成したり異世界の創造者のアップデートに対応したりしていくのは手間がかかります。
なのでunion.jsからd.tsファイルを自動生成できるとよいと思います。

**Comment by Spoonail-Iroiro** [comment]
内容自体ではないのですが1つ懸念点がありまして、これはmaginaiとは別のパッケージとしたほうがいいのではないかと思っています。
理由としては、union.jsの型はゲームバージョンの更新に追従して更新したくなると思うのですが、maginaiの方はゲームバージョンが上がっても必ずしも更新するとは限らないためです。
またバージョン表記自体もunion.jsの型パッケージバージョンがゲームバージョンとシンクロしていたほうがわかりやすいかと思います。
（いせそうが微妙にSemVerに沿ってないという問題はありますが…）

どうしましょうか
union.js型定義パッケージとそのリポジトリの作成・公開、enzakiさんの方でされるのならそれでもいいですし、私の方で作ってしまってもいいですし

**Comment by soeklgb** [comment]
別のパッケージにすることに賛成です。よく考えたらmaginaiに依存していないですし分けたほうが良いですね。
リポジトリの作成はSpoonailさんのほうでお願いします。

**Comment by Spoonail-Iroiro** [comment]
一応確認なのですが型パッケージは以下のようにしようと思っています
- パッケージ名はmaginai-game-types
  - @types/～にしないのは非公式のため&&型付け対象であるunion.jsもそれ単体の利用を目的としたものではないので…
- LicenseはMIT
  - Copyrightはenzakiさんと私にしようと思っています
    - メインソースはenzakiさん、ビルドスクリプト等は私という分担な漢字で
上記仕様でなにか問題があればお知らせください

**Comment by soeklgb** [comment]
問題ありません！よろしくお願いします。

**Comment by Spoonail-Iroiro** [comment]
https://github.com/Spoonail-Iroiro/maginai-game-types

maginai-game-typeをリリースしましたのでcloseします🙌
