### ISSUE TITLE
Windowsでnpm installに失敗する

### ISSUE THREAD

**Issue by soeklgb** [Spoonail-Iroiro/maginai#20]
tools/release.jsで使用されているzipコマンドがWindowsでは使えないのが原因のようです。

**Comment by Spoonail-Iroiro** [comment]
なるほど
- prepareに`npm run build`を入れた
- `npm run build`では型パッケージとしてのビルドと配布物のビルド（ここでzip使用）を行う

という更新を入れたのですが、`npm install`でprepareが走るのでコケる感じですね…
ちょっと見てみます　
横着しないで型パッケージのビルドと配布物のビルドコマンドをちゃんと分ければよかったのですがｗ
