### ISSUE TITLE
loglevelの初期化がされていない

### ISSUE THREAD

**Issue by soeklgb** [Spoonail-Iroiro/maginai#30]
logging.jsがどこからもインポートされておらず、loglevelの初期化とプラグインの適用が行われていません。
その結果、Chromeではprefix（[INFO][maginai]の部分）が表示されず、Firefoxではログ自体が表示されなくなっています。

**Comment by Spoonail-Iroiro** [comment]
ありがとうございます🙏
修正版をv0.3.1としてすぐ出せると思います
