### ISSUE TITLE
Steam実績の取得を無効化する

### ISSUE THREAD

**Issue by soeklgb** [Spoonail-Iroiro/maginai#40]
必須機能です。

**Comment by Spoonail-Iroiro** [comment]
うーん
全部のゲームでMod＝実績取得無効ではないので微妙なところかなと…

**Comment by soeklgb** [comment]
調べてみると実績を無効化しないゲームも結構ありますね...勝手に必須のものだと思ってました。

**Comment by Spoonail-Iroiro** [comment]
ちなみに実績を無効化するゲームでも、結局実績の無効化を無効化するModが結構出てるみたいです

**Comment by soeklgb** [comment]
Steamの実績を解除するツールがあるのを知ってしまうとModで少し簡単に実績を解除するのはもはや問題とは思えませんね...
