### ISSUE TITLE
メソッドパッチを、パッチ後メソッドを直接渡すようにして簡易化

### ISSUE THREAD

**Issue by Spoonail-Iroiro** [Spoonail-Iroiro/maginai#44]
現行の`Patcher.patchMethod`の使用方法を以下のケース等で間違えやすいので使いやすくしたい
- パッチ後メソッドでthisを使うのに通常の関数（function）ではなくアロー関数にしてしまう
- 「パッチ後メソッドを返す関数を渡す」のがわかりにくい

今のところの新案として具体的には
```js
// 元のメソッドを呼び出してそのまま結果を返すメソッドでパッチ
maginai.patcher2.patchMethod(tGameClass, 'methodName', (self, args, original, context) => {
  return original.call(self, ...args);  
})
```
のような形で直接パッチ後のメソッドを渡すようにするインターフェースに変更する。
この形だと元々のthisを引数selfとして明示的に渡すようにしているのでアロー関数も使える。

パッチ後関数への引数は要検討
- 上記の例ではself（メソッドのthis）, args（メソッドに渡された引数）, original（元のメソッド）, context（その他のcontext情報）
- JsPosedのようにcontextオブジェクト下に全部入れてしまう手もあるがcontextに何が入っているか見えにくくなるのが気になる
  - self/args/originalは使用頻度が高い（元のメソッドをそのまま呼び出すのに使う）ため個別に引数としてあってよいように思う

**Comment by soeklgb** [comment]
`call`は戸惑いやすいので`original`をラップして`original(...args)`で呼べるようにしてもいいと思う。callのself部分にself以外が渡されるケースが思いつかない。
あと質問なんですけどcontextって何が入る予定なんでしょうか？

**Comment by Spoonail-Iroiro** [comment]
あー確かに事前にbindしてしまえばいいのか

contextはself・args・original以外の呼び出し時情報を持つオブジェクトのイメージだったけど今のところ具体的に思いつかないのでなしでもいいかも（後から引数増やしても問題ないし）
