### ISSUE TITLE
`saveLoading`イベントを追加する

### ISSUE THREAD

**Issue by Spoonail-Iroiro** [Spoonail-Iroiro/maginai#59]
セーブデータが選択されて、各ゲームオブジェクトへのデータのセットが始まる前のイベント`saveLoading`を追加する。
`saveLoading`イベントではMod用セーブオブジェクトへのアクセスができる。

理由：
`maginai.modSave`でのMod用セーブオブジェクトの取得を`saveLoaded`イベントで行うと、イベントより前の処理をセーブデータに保存された値に基づいて行えないため。
たとえば`tGameRoutineMap.viewMap`は`saveLoaded`イベントより前に呼ばれるため、`tGameRoutineMap.viewMap`にメソッドパッチした場合、そのメソッドは`saveLoaded`イベントが起こるより前に呼ばれてしまう。

`saveLoading`イベントと`saveLoaded`イベントの使い分け・原則は以下の通り
- `maginai.modSave`でのMod用セーブオブジェクトの取得は`saveLoading`イベントで行う
- セーブデータからすべてのデータ（たとえば`tGameCharactor.charas`に格納されたキャラ情報等）がロードされセットされた直後に行いたい処理は`saveLoaded`イベント （従来通り）

考慮事項
- `saveLoading`名称が適切かどうか
  - `modSaveLoaded`? 
- `maginai.modSave`の使用例の更新

**Comment by soeklgb** [comment]
`modSave`の取得の仕方ですが、`maginai.modSave`で取得するより以下のように引数で明示的に渡すのが良いと思います。
```js
maginai.events.saveLoading.addHandler((modSave) => {
  modSave.getSaveObject("mod");
};

maginai.events.saveObjectRequired.addHandler((modSave) => {
  modSave.setSaveObject("mod", save);
};
```
`maginai`からの取得だと個々のセーブデータとは別に保存できるように感じるかもしれません。

個人的にはこんなインターフェースが好みです。
```js
maginai.modSave.load(modName, (modData) => {
});

maginai.modSave.save(modName, () => {
  return modData;
});
```

**Comment by Spoonail-Iroiro** [comment]
いっそ`modSave`にはこのくらいのヘルパー関数`addSaveHandlers`があってもいいかもしれない

```js
let myModValue = 0;
const createSaveObject = () => ({myModValue});
const loadSaveObject = (modSaveObject) => myModValue = modData.myModValue;
maginai.modSave.addSaveHandlers(
  'myMod',
  createSaveObject,
  loadSaveObject
);
```
この`addSaveHandlers`の呼び出しは下記のコードと同じ
```js
maginai.events.saveLoading.addHandler(() => {
  const modSaveObject = maginai.modSave.getSaveObject('myMod');
  loadSaveObject(modSaveObject);
};

maginai.events.saveObjectRequired.addHandler(() => {
  const modSaveObject = createSaveObject();
  maginai.modSave.setSaveObject('myMod', modSaveObject);
};
```

**Comment by Spoonail-Iroiro** [comment]
下段のコードの通り、イベント`saveLoading`/`saveObjectRequired`の方はイベント引数なしでいきたい
理由：
個人的にはイベントハンドラで`modSave`サブモジュールを引数で受け取れてもあまりわかりやすくならないように見えるため。
enzaki氏の2番目の例のように直接Mod用セーブオブジェクトを受け取れればわかりやすいが、そのためにはmaginai側は`addHandler`時点でMod名を受け取る必要があり`addHandler`のインターフェースにそぐわない。

**Comment by Spoonail-Iroiro** [comment]
補足：
`modSave.addSaveHandlers`はほぼenzaki氏の`save`/`load`を1つのメソッドにまとめたメソッドだが、変更点と変更理由は以下の通り。

■2つあるメソッドを1つに統合
結局この`modSave.addSaveHandlers`がhigh-level APIで`modSave.getSaveObject`/`modSave.setSaveObject`/`events.saveLoading`/`events.saveObjectRequired`がlow-level APIという関係になるので
`modSave.addSaveHandlers`は便利な、ワンストップなメソッドとしていいのではないか、という理由。

■名前をハンドラー登録ということをわかりやすく
`save`/`load`だとどうしてもすぐセーブ・ロードを実行するように見えるのと、個別のセーブデータがセーブ/ロードされるたびにハンドラーが呼び出されるように見えにくいため。

**Comment by soeklgb** [comment]
わたしの出した最初の例ですが、`modSave`を`saveLoading`と`saveObjectRequired`の外で使う理由がないことをAPIレベルで表現したほうがよいのでは、という意図でした。（javascriptなのでルールに違反することは簡単ですが）言葉足らずですみません。

**Comment by soeklgb** [comment]
> ```js
> maginai.modSave.load(modName, (modData) => {
> });
> 
> maginai.modSave.save(modName, () => {
>   return modData;
> });
> ```

こっちの例は他のModのセーブデータにアクセスしてはいけない、というのをAPIで表現したものです。

> ```js
> maginai.events.saveLoading.addHandler(() => {
>   const modSaveObject = maginai.modSave.getSaveObject('myMod');
>   loadSaveObject(modSaveObject);
> };
> 
> maginai.events.saveObjectRequired.addHandler(() => {
>   const modSaveObject = createSaveObject();
>   maginai.modSave.setSaveObject('myMod', modSaveObject);
> };
> ```

これだとドキュメントを読み込まないと正しいAPIの使い方ができないのでは？と思います。
`maginai.events.saveLoading`は`maginai.modSave.getSaveObject`以外を目的に使われて、`maginai.modSave.getSaveObject`は`maginai.events.saveLoading`以外で使われることになります。
たとえlow-level APIであれど意図しない使い方を可能にする理由はありません。

low-level APIで簡単に他のModのセーブデータにアクセスできるのなら`modSave.addSaveHandlers`はなくても良いでしょう。

> `save`/`load`だとどうしてもすぐセーブ・ロードを実行するように見えるのと、個別のセーブデータがセーブ/ロードされるたびにハンドラーが呼び出されるように見えにくいため。

`save`/`load`の命名に関してはその通りだと思います。

**Comment by Spoonail-Iroiro** [comment]
> 他のModのセーブデータにアクセス

これについてはあるModをさらに拡張するMod等でありうるユースケースだとは思ってる

**Comment by Spoonail-Iroiro** [comment]
これらの、Mod用セーブデータの操作インターフェースについて
最終的にはどういう形がいいと思ってます？

**Comment by soeklgb** [comment]
```js
maginai.modSave.addLoadHandler(modName, (modData) => {
});

maginai.modSave.addSaveHandler(modName, () => {
  return modData;
});
```
このような`save`/`load`をハンドラだと分かる命名にしたものがいいと思ってますが、既存のハンドラのインターフェースにそぐわないと言われたらそうですね。

Modのセーブデータにいつでもどこからでも触れるようにするのなら`maginai.events.saveLoading.addHandler`/`maginai.modSave.getSaveObject`のほうがいいと思います。

**Comment by Spoonail-Iroiro** [comment]
> いっそ`modSave`にはこのくらいのヘルパー関数`addSaveHandlers`があってもいいかもしれない
> 
> ```js
> let myModValue = 0;
> const createSaveObject = () => ({myModValue});
> const loadSaveObject = (modSaveObject) => myModValue = modData.myModValue;
> maginai.modSave.addSaveHandlers(
>   'myMod',
>   createSaveObject,
>   loadSaveObject
> );
> ```
> 
> この`addSaveHandlers`の呼び出しは下記のコードと同じ
> 
> ```js
> maginai.events.saveLoading.addHandler(() => {
>   const modSaveObject = maginai.modSave.getSaveObject('myMod');
>   loadSaveObject(modSaveObject);
> };
> 
> maginai.events.saveObjectRequired.addHandler(() => {
>   const modSaveObject = createSaveObject();
>   maginai.modSave.setSaveObject('myMod', modSaveObject);
> };
> ```

これで実装したい
ただし`addSaveHandlers`は少し変更
- 名前を`addSaveHandler`→`addSaveObjectHandler`に
- ロード時のハンドラーにisNewGameを渡すように（`saveLoaded`と同様）

```js
let myModValue = 0;
const createSaveObject = () => ({myModValue});
const loadSaveObject = (modSaveObject, isNewGame) => {
  if (isNewGame) {
    myModValue=1;
  }
  else {
    myModValue = modSaveObject?.myModValue ?? 2;
  }
};
maginai.modSave.addSaveObjectHandlers(
  'myMod',
  createSaveObject,
  loadSaveObject
);
```

**Comment by soeklgb** [comment]
一応確認です。実装するのはこの三つですか？
- `maginai.events.saveLoading`
- `maginai.events.saveObjectRequired`
- `maginai.modSave.addSaveObjectHandlers`

**Comment by Spoonail-Iroiro** [comment]
* `maginai.events.saveLoading`
* `maginai.modSave.addSaveObjectHandlers`

この2つです。

`maginai.events.saveObjectRequired`はすでに存在していますね。

**Comment by Spoonail-Iroiro** [comment]
今更ながら「ロード時に`name`に対応するセーブオブジェクトが存在しない」ときのhandlerは別にしたほうがいいのではとなった

```js
let myModValue = 0;
const initializeWithoutSaveObject = (isNewGame) => {
  myModValue = isNewGame ? 1 : 2;
}
const loadSaveObject = (modSaveObject) => {
  myModValue = modSaveObject.myModValue;
};
const createSaveObject = () => ({myModValue});
maginai.modSave.addSaveObjectHandlers(
  'myMod',
  initializeWithoutSaveObject,
  loadSaveObject,
  createSaveObject,
);
```
これは以下と同じ
```js
maginai.events.saveLoading.addHandler((e) => {
  const modSaveObject = maginai.modSave.getSaveObject('myMod');
  if (modSaveObject === undefined) {
    initializeWithoutSaveObject(e.isNewGame);
  }
  else {
    loadSaveObject(modSaveObject);
  }
};

maginai.events.saveObjectRequired.addHandler(() => {
  const modSaveObject = createSaveObject();
  maginai.modSave.setSaveObject('myMod', modSaveObject);
};
```



参考：https://github.com/limoka/DSP-Mods/blob/master/Mods/DSPModSave/src/DSPModSave/IModCanSave.cs
